### PR TITLE
Translate README

### PR DESCRIPTION
**Pull request by yousef157**
I know there are a lot of problems, but if you can figure it out yourself, please fix it.

### CODE REVIEW

**Comment by sendevia** [comment]
Thank's very much for your work! really nice translate!😆 and I will try hard to fix these mistake too!😄
Sorry, my English is not well...😔

**Comment by yousef157** [comment]
> Thank's very much for your work! really nice translate!😆 and I will try hard to fix these mistake too!😄
> Sorry, my English is not well...😔

It's ok! I know you are Chinese..

**Comment by yousef157** [comment]
What the fuck was me 1 year ago

**Comment by sendevia** [comment]
@yousef157 🤔

**Comment by yousef157** [comment]
I want to fucking die

**Pull request merged**
